// AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// JOBS
export const ALL_JOBS_REQUEST = "ALL_JOBS_REQUEST";
export const ALL_JOBS_LOADING = "ALL_JOBS_LOADING";
export const ALL_JOBS_LOADED = "ALL_JOBS_LOADED";